[project]
name = "client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "econagents[all]>=0.0.5",
    "jinja2>=3.1.6",
    "python-dotenv>=1.1.0",
]
