[project]
name = "public-goods-simple"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "httpx>=0.28.1",
    "otree>=5.11.2",
    "requests>=2.32.3",
    "ws4py>=0.6.0",
]
